modLoader="javafml"
loaderVersion="[34,)"
license="CC BY-NC-SA 3.0 Unported"
issueTrackerURL="https://github.com/Eltrut-Co/Lepton/issues"
[[mods]]
modId="lepton"
version="1.2.6"
displayName="Lepton"
logoFile="lepton.png"
credits="EltrutLikes"
authors="Eltrut & Co."
description='''
Smallest things.
'''

[[dependencies.lepton]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lepton]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3, 1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.lepton]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[3.0.0,)"
    ordering="AFTER"
    side="BOTH"